ekzamen/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
   # path('ekzamen/', include('ekzamenator.urls')),

    path('vhod/', include("ekzamenator.urls")),
    path('ekzamen/', include("ekzamenator.urls_ekzamen")),
    path('admin/', admin.site.urls),
]

ekzamenator/urls.py
from django.urls import path

from . import views

urlpatterns = [
   # path("", views.UsersView.as_view()),
 #   path ('ekzamen/', ekzamen, name='ekzamen'),
# path ('add/', views.UsersCreateView.as_view(), name='add'),
   path('', views.vhod, name='vhod'),
    ]

ekzamenator/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Shu(models.Model):
    """шахтоуправление"""
    name = models.CharField("Шахто-управление", max_length=150)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Шахто-управление"
        verbose_name_plural = "Шахто-управления"

class Prof(models.Model):
    """Прафесия"""
    name = models.CharField("Праффесия", max_length=150)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Праффесия"
        verbose_name_plural = "Праффесии"

class Pp(models.Model):
    """Дроизводственое подраздиление"""
    name = models.CharField("Дроизводственое подраздиление", max_length=150)
    shu = models.ForeignKey(
        Shu, verbose_name="Шахто-управление", on_delete=models.SET_NULL, null=True
    )
    user = models.ForeignKey(User, verbose_name="Пользователь", null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Дроизводственое подраздиление"
        verbose_name_plural = "Дроизводственое подраздиления"
        ordering = ("name", "shu")

class Uch(models.Model):
    """Участок"""
    name = models.CharField("Участок", max_length=150)
    shu = models.ForeignKey(
        Shu, verbose_name="Шахто-управление", on_delete=models.SET_NULL, null=True
    )
    pp = models.ForeignKey(
        Pp, verbose_name="Дроизводственое подраздилени", on_delete=models.SET_NULL, null=True
    )
    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Участок"
        verbose_name_plural = "Участки"
        ordering = ("name", "shu", "pp")

class Users(models.Model):
    """Люди"""
    name = models.CharField("Фамилия И.О.", max_length=150)
    nomer = models.PositiveIntegerField("Номер", unique=True)
    prof = models.ForeignKey(
        Prof, verbose_name="Проффесия", on_delete=models.SET_NULL, null=True
    )
    shu = models.ForeignKey(
        Shu, verbose_name="Шахто-управление", on_delete=models.SET_NULL, null=True
    )
    pp = models.ForeignKey(
        Pp, verbose_name="Производственое подраздилени", on_delete=models.SET_NULL, null=True
    )
    uch= models.ForeignKey(
        Uch, verbose_name="Участок", on_delete=models.SET_NULL, null=True
    )
   # url = models.SlugField(max_length=130, unique=True)
    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("users_detail", kwargs={"slug": self.id})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def get_update_url(self):
        return reverse("users_update", kwargs={"id": self.id})

    class Meta:
        verbose_name = "Человек"
        verbose_name_plural = "Люди"

        ordering = ("name", "nomer", "shu", "pp", "uch", "prof")


#class UserProfile(models.Model):
 #   user = models.OneToOneField(User)
#    avatar = models.ImageField(upload_to='images/users', verbose_name='Изображение')
#    pp = models.ForeignKey(Pp, verbose_name="Производственое подраздилени", on_delete=models.SET_NULL, null=True)


#   def __unicode__(self):
 #       return self.user
  #  class Meta:
   #     verbose_name = 'Профиль'
    #    verbose_name_plural = 'Профили'

ekzamenator/forms.py
from  django.forms import  ModelForm
from  django import forms
from  .models import Users,Pp, Shu, Prof, Uch
from django.contrib.auth.models import User

class UsersForm(ModelForm):

    name = forms.CharField(label="Ф.И.О.", max_length=150)
    nomer = forms.IntegerField(label="Таб.№")
    prof = forms.ModelChoiceField(queryset= Prof.objects.all(),
                                   label="Профессия")
    uch = forms.ModelChoiceField(queryset=Uch.objects.all(),
                                  label="Участок")

    shu = forms.ModelChoiceField(queryset= Shu.objects.all(),
                                 label='Шахто управление', help_text='Не забудьту задать шахтоуправление!',
                                 initial = 1, widget=forms.widgets.Select(attrs={'size': 1}))
    pp = forms.ModelChoiceField(queryset=Pp.objects.all(),
                                 label="Шахта")

    name.widget.attrs.update({'class': 'form-control'})
    nomer.widget.attrs.update({'class': 'form-control'})
    prof.widget.attrs.update({'class': 'form-control'})
    shu.widget.attrs.update({'class': 'form-control'})
    pp.widget.attrs.update({'class': 'form-control'})
    uch.widget.attrs.update({'class': 'form-control'})
    
    def __init__(self,  *args, **kwargs):
        user = kwargs.pop('user')
        super(UsersForm, self).__init__(*args, **kwargs)

        self.fields['pp'].queryset = Pp.objects.filter(user = user)
       #user = User.objects.get(id=1)
        ppp = Pp.objects.filter(user=user)

        self.fields['uch'].queryset = Uch.objects.filter(pp = ppp[0])
        #self.fields['shu'].queryset = Shu.objects.filter(pp=ppp[0])
    class Meta:
        model = Users
        fields = ('name', 'nomer', 'prof','shu', 'pp', 'uch')

class UpdateForm(forms.ModelForm):
    """ Форма добавления тикетов
    """
    name = forms.CharField(label="Ф.И.О.", max_length=150)
    nomer = forms.IntegerField(label="Таб.№")
    prof = forms.ModelChoiceField(queryset=Prof.objects.all(),
                                  label="Профессия")
    shu = forms.ModelChoiceField(queryset=Shu.objects.all(),
                                 label='Шахто управление', widget=forms.widgets.Select(
            attrs={'class': 'disabled', 'readonly': 'readonly'}))
    uch = forms.ModelChoiceField(queryset=Uch.objects.all(),
                                 label="Участок")
    name.widget.attrs.update({'class': 'form-control flex-fill'})
    nomer.widget.attrs.update({'class': 'form-control flex-fill'})
    prof.widget.attrs.update({'class': 'form-control flex-fill'})
    uch.widget.attrs.update({'class': 'form-control flex-fill'})


    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.fields['pp'].queryset = Pp.objects.filter(user=self.user)
    # user = User.objects.get(id=1)
        ppp = Pp.objects.filter(user=self.user)

        self.fields['uch'].queryset = Uch.objects.filter(pp=ppp[0])

    # self.fields['shu'].queryset = Shu.objects.filter(pp=ppp[0])
    class Meta:
        model = Users
        fields = ('name', 'nomer', 'prof', 'shu', 'pp', 'uch')


class UchForm(ModelForm):
    name = forms.CharField(label="Введите название участка", max_length=150)
    shu = forms.ModelChoiceField(queryset=Shu.objects.all(),
                                 label='Шахто управление', help_text='Не забудьту задать шахтоуправление!',
                                 initial=1, widget=forms.widgets.Select(attrs={'size': 1}))
    pp = forms.ModelChoiceField(queryset=Pp.objects.all(),
                                label="Шахта")
    name.widget.attrs.update({'class': 'form-control flex-fill'})
    class Meta:
        model = Uch
        fields = ('name', 'shu', 'pp',)

    #def __init__(self, *args, **kwargs):
    #    user = kwargs.pop('user')
   #     super(UchForm, self).__init__(*args, **kwargs)

       # self.fields['pp'].queryset = Pp.objects.filter(user=user)
        # user = User.objects.get(id=1)
        #ppp = Pp.objects.filter(user=user)

        #self.fields['uch'].queryset = Uch.objects.filter(pp=ppp[0])
        # self.fields['shu'].queryset = Shu.objects.filter(pp=ppp[0])

ekzamenator/views.py
from django.conf import settings
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView
from django.views.generic.base import View
from django.shortcuts import render
from django.urls import  reverse_lazy, reverse
from  django.views.generic.edit import CreateView
from  django.contrib import auth
from  django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UsersForm, UpdateForm, UchForm
from  .models import Users, Pp, Uch, Shu
from django.contrib.auth.models import User

class UchListView(LoginRequiredMixin, ListView):
   """Список фильмов"""
   model = Uch
   queryset = Uch.objects.all()
   template_name = 'ekzamenator/uch_list.html'
   paginate_by = 10

   def get_context_data(self, **kwargs):
       ppp = Pp.objects.filter(user=self.request.user)
       new_uch = Uch.objects.filter(pp=ppp[0])

       context = super(UchListView, self).get_context_data(**kwargs)
       # Добавляем новую переменную к контексту и иниуиализируем ее некоторым значением
       #   pp = Pp.object.all().name
       context['Ptemp'] = ppp
       context['uch_list'] = new_uch
       return context




class UchUpdate(LoginRequiredMixin, UpdateView):
    model = Uch
   # slug_field = "pk"
    #form_class = UsersForm
    form_class = UchForm
    template_name = "ekzamenator/update_uch.html"
    success_url = reverse_lazy("Uch_List")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ppp = Pp.objects.filter(user=self.request.user)
        shus = Shu.objects.filter(pp=ppp[0])
        context['Ptemp'] = ppp
        context['users_list'] = shus
        return context


class UchCreateView(LoginRequiredMixin, CreateView):
   template_name = 'ekzamenator/add_uch.html'
   form_class = UchForm
   success_url = reverse_lazy("Uch_List")

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       ppp = Pp.objects.filter(user=self.request.user)
       shus = Shu.objects.filter(pp=ppp[0])
       context['Ptemp'] = ppp
       context['users_list'] = shus
       return context


class UchDelete(LoginRequiredMixin, View):
    def get(self, request, id):
        uch = get_object_or_404(Uch, id=id)
        ppp = Pp.objects.filter(user=self.request.user)
        shus = Shu.objects.filter(pp=ppp[0])

        return render(request, 'ekzamenator/delete_uch.html',
                     context={'uch':uch, 'Ptemp': ppp, 'users_list': shus})

    def post(self, request, id):
        uch = get_object_or_404(Uch, id=id)
        uch.delete()
        return redirect(reverse("Uch_List"))


class UsersView(LoginRequiredMixin, ListView):
   """Список фильмов"""
   model = Users
   queryset = Users.objects.all()
  # ppp = Pp.objects.get(name="")


   paginate_by = 10

   def get_context_data(self, **kwargs):
       ppp = Pp.objects.filter(user=self.request.user)
       new_users = Users.objects.filter(pp=ppp[0])
       context = super(UsersView, self).get_context_data(**kwargs)
       # Добавляем новую переменную к контексту и иниуиализируем ее некоторым значением
    #   pp = Pp.object.all().name
       context['Ptemp'] = ppp
       context['users_list'] = new_users
       return context

class UsersDetailView(LoginRequiredMixin, DetailView):
   """Полное описание фильма"""
   model = Users
   slug_field = "id"

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       ppp = Pp.objects.filter(user=self.request.user)
       shus = Shu.objects.filter(pp=ppp[0])
       context['Ptemp'] = ppp
       context['users_list'] = shus
       return context

def ekzamen(request):
   pp = Pp.objects.all()
   pp_col = Pp.objects.all().count()
   user = Users.objects.all()
   user_col = Users.objects.all().count()
   context = {'pp': pp, 'pp_col': pp_col, 'user': user, 'user_col': user_col}

   return render(request, 'ekzamenator/index.html', context)


class UsersCreateView(LoginRequiredMixin, CreateView):
   template_name = 'ekzamenator/add_user.html'
   form_class = UsersForm
   success_url = reverse_lazy("Users_View")

   def get_context_data(self, **kwargs):

      context = super().get_context_data(**kwargs)
      context['users'] = Users.objects.all()
      ppp = Pp.objects.filter(user=self.request.user)
      shus= Shu.objects.filter(pp=ppp[0])
      context['Ptemp'] = ppp
      context['users_list'] = shus
      return context

   def get_form_kwargs(self):
       kwargs = super(UsersCreateView, self).get_form_kwargs()
       kwargs.update({'user': self.request.user})
       return kwargs


"""
class UsersUpdate(LoginRequiredMixin, View):
   def get(self, request, id):
      users = get_object_or_404(Users, id=id)

      bound_form = UsersForm(instance=users)
      return render(request, 'ekzamenator/update_user.html', context={'form': bound_form, 'users': users})

   def post(self, request, id):
      users = get_object_or_404(Users, id=id)
      bound_form = UsersForm(request.POST, instance=users)
      if bound_form.is_valid():
          new_user = bound_form.save()
          return redirect(new_user)

      return render(request, 'ekzamenator/update_user.html', context={'form': bound_form, 'users': users})
"""
class UsersDelete(LoginRequiredMixin, View):
   def get(self, request, id):
      users = get_object_or_404(Users, id=id)
      ppp = Pp.objects.filter(user=self.request.user)
      shus = Shu.objects.filter(pp=ppp[0])

      return render(request, 'ekzamenator/delete_user.html', context={'users': users, 'Ptemp': ppp, 'users_list': shus})

   def post(self, request, id):
      users = get_object_or_404(Users, id=id)
      users.delete()
      return redirect(reverse("Users_View"))


class UsersUpdate(LoginRequiredMixin, UpdateView):
    model = Users
   # slug_field = "pk"
    #form_class = UsersForm
    form_class = UpdateForm
    template_name = "ekzamenator/update_users.html"
    success_url = reverse_lazy("Users_View")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ppp = Pp.objects.filter(user=self.request.user)
        shus = Shu.objects.filter(pp=ppp[0])
        context['Ptemp'] = ppp
        context['users_list'] = shus
        return context

    def get_form_kwargs(self):
        kwargs = super(UsersUpdate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class Search(ListView):
    """Поиск Людей"""
    paginate_by = 3

    def get_queryset(self):
        ppp = Pp.objects.filter(user=self.request.user)
        #new_users = Users.objects.filter(pp=ppp[0])
        fusers =Users.objects.filter((Q(nomer__icontains=self.request.GET.get("q")) |
                                    Q(name__icontains=self.request.GET.get("q")))
                                         &Q(pp=ppp[0]))
        return fusers



    def get_context_data(self, *args, **kwargs):
        #  context = super(UsersView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и иниуиализируем ее некоторым значением
        #   pp = Pp.object.all().name
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

def vhod(request):
    listings = Pp.objects.all();  # order_by('-name').filter(user__icontains=request.user)

    context = {'listings': listings}
    return render(request, "ekzamen/vhod.html", context)

def PpViewList(request):
    listings = Pp.objects.filter(user=request.user)
    #names = list.listings.name
    context = {'listings': listings}
    return render(request, 'ekzamenator/pp_view.html', context)

templates/ekzamenator/add_user.html
{% extends "ekzamenator/basic.html" %}
{% block title %}Добавление человека{% endblock %}
{% block content %}

<div class="row col-12 justify-content-center mt-5">
	<div class="shadow-lg card shadow-lg border-success text-white-50 bg-dark py-2 px-5 mt-3 " style="width: 24rem;">

<form action="{% url 'UsersCreateView' %}" method="post">
    {% csrf_token %}
<!--    {{ form.as_p }}-->

     <p>{{ form.name.label}}:<br>{{ form.name }}</p>
     <p>{{ form.nomer.label}}:<br>{{ form.nomer }}</p>
    <p>{{ form.prof.label}}:<br>{{ form.prof }}</p>
    <p>{{ form.uch.label}}:<br>{{ form.uch }}</p>

    {% for p2 in Ptemp %}
    <input type="hidden" name="pp" class="form-control" id="id_pp" value="{{ p2.id }}">
     {% endfor %}
     {% for p2 in users_list %}
    <input type="hidden" name="shu" class="form-control" id="id_shu" value="{{ p2.id }}">
     {% endfor %}
<center>
    <button class="btn btn-success" type="submit">Добавить</button>
</center>
<!--
    {% for p2 in Ptemp %}

              <p>{{ p2.name}}<br></p>
                 <p>{{ p2.shu}}<br></p>
             {% endfor %}
             -->
</form>


    </div>
 </div>
    {% endblock %}

templates/ekzamenator/basic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="shortcut icon" type="images/x-icon" href="{% static 'favicon.ico' %}">
 <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    -->
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->



    <!--
    <meta name="keywords" content="Свердловск, svkmarket, ЛНР, объявления, маркет, покупки, Aliexpress, shop, market, заказы, бизнесс, заработать, разработка сайтов, услуги" />
<meta name="description" content="Заказы с Aliexpress, выгодное предложение, быстрая доставка, бесплатные объявления, канал Telegram @svkmarker, электронная комерция">

-->
|<style>
footer {
    position: absolute;
    bottom: 0;
    width: 100%;
    height: 2vh; /*высота футера будет зависеть от высоты экрана*/
}
/* чтобы весь футер заливался */

html,body{
    height:100%;
     background-color: #000000;
}


</style>
</head>

<body>





  <!-- NAV #1 и HEADER -->
<div class="container col-12">
	<div class="row bg-dark">


<nav class="navbar navbar-expand-md navbar-dark bg-dark col-12 fixed-top">
			<div class="col-1">

				<a class="navbar-brand text-success" href="/" data-placement="top" title="Главная страница"><img src="/static/logo.png" width="32" height="32">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</a>
                		</div>
              <div class="col-3 text-success">
                    <table>
<tbody>
    <tr><td>{% for p1 in Ptemp %} {{ p1.name }}{% endfor %}</td></tr>
    <tr><td>
                <div class="text-warning">
          {% block title %}

    {% endblock %}
                </div>
        </td></tr>
 </tbody>
</table>


</div>




{% if user.is_authenticated %}
     <div class="col-3">
  <form action="{% url 'search' %}" method="get" class="d-flex editContent">
        <input type="search" placeholder="Введите номер или ФИО" name="q" class="form-control" required="">
        <button type="submit"  class="btn btn-success">
            <span class="fa fa-search" aria-hidden="true"></span>
        </button>
    </form>
     </div>


       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
  <span class="fa fa-bars" aria-hidden="true"></span>
 </button>

 <!--Само меню-->


 <div class="collapse navbar-collapse" id="navbarResponsive">

 <ul class="navbar-nav ml-auto  d-flex justify-content-end">


        	<li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" data-placement="top" title="Управление работниками" href="#" id="navbarDropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Работник</a>
        <div class="bg-dark dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="dropdown-item text-warning" href="/ekzamen/usersview/" data-placement="top" title="Просмотр списка работников" >
                 <span class="fa fa-users fa-1x" aria-hidden="true"></span>
                 Все</a>
            <a class="dropdown-item text-warning" href="/ekzamen/add/" data-placement="top" title="Добавить работника" >
                  <span class="fa fa-user-plus fa-1x" aria-hidden="true"></span>
                                Добавить</a>


        </div>

            </li>
     <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="/ekzamen/ppview/"  id="navbarDropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-placement="top" title="Управление участками" >Участки</a>


       <div class="bg-dark dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="dropdown-item text-warning" href="/ekzamen/uchlist/" data-placement="top" title="Просмотр списка участков" >
                            <span class="fa fa-list-ol" aria-hidden="true"></span>
                 Все</a>
            <a class="dropdown-item text-warning" href="/ekzamen/uchadd/" data-placement="top" title="Добавить участок">
                              <span class="fa fa-plus-square" aria-hidden="true"></span>
                Добавить</a>


        </div>
</li>
   <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="/ekzamen/ppview/"  id="navbarDropdownMenuLink"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-placement="top" title="Управление профессиями">Профессии</a>


       <div class="bg-dark dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="dropdown-item text-warning" href="/ekzamen/uchlist/" data-placement="top" title="Просмотр списка профессий">
                     <span class="fa fa-list-ol" aria-hidden="true"></span>
                 Все</a>
            <a class="dropdown-item text-warning" href="/ekzamen/uchadd/" data-placement="top" title="Добавить профессию">
                 <span class="fa fa-plus-square" aria-hidden="true"></span>
                Добавить</a>


        </div>
</li>
        	<li class="nav-item"><a href="/ekzamen/ppview/" class="nav-link">Отчеты</a></li>




     <li class="nav-item"><a href="/" class="nav-link text-info"> {% for p1 in Ptemp %} {{ p1.user }}{% endfor %}</a></li>


		<li class="active nav-item"><a href="{% url 'logout'%}" class="nav-link" data-placement="left" title="Выйти из учетной записи">Выход</a></li>
        </ul>
 </div><!-- /.navbar-collapse -->
    {% endif %}
</nav>


      </div>

 </div>
<!--
{% if user.is_authenticated %}
  <div class="container bg-dark align-self-start col-12" >
        <div class="row bg-dark col-12 d-flex justify-content-center" >
  {% for p1 in Ptemp %}
     <p class="text-success text-center">Вы вошли как - {{  p1.user  }}-{{ p1.name }} </p>


{% endfor %}

  {% endif %}
  -->
  <!--
  начало блока
  -->




    {% block content %}

    {% endblock %}
  <!--
  конец блока
  -->




   {% include 'ekzamenator/footer.html' %}

templates/ekzamenator/delete_user.html
{% extends "ekzamenator/basic.html" %}
{% block title %}Удалить человека "{{ users.name|title }}"{% endblock %}
{% block content %}
<div class="row col-12 justify-content-center mt-5">
	<div class="shadow-lg card shadow-lg border-success text-white-50 bg-dark py-2 px-2 mt-5 " style="width: 24rem;">

<form action="{% url 'users_delete' id=users.id %}" method="post">
    {% csrf_token %}
    <center>
        <h4 class="text-warning">Подтвердите удаление </h4>
        <h3 class="text-danger">{{ users.name|title }}</h3>
<br>

    <a class="btn btn-success" href="{{ users.get_absolute_url }}">Отменить</a>



    <button type="submit" name="button" class="btn btn-danger">
        Удалить
    </button>

        </center>
</form>
    </div>
</div>

    {% endblock %}

templates/ekzamenator/users_detail.html
{% extends "ekzamenator/basic.html" %}
{% block content %}


<div class="row col-12 justify-content-center mt-5 text-success">
	<div class="shadow-lg card shadow-lg border-success text-white-50 bg-dark py-2 px-2 mt-3 " style="width: 22rem;">
<center>
				<H3>Сведения о работнике</H3>
		<p>Таб.№ - {{ users.nomer }}</p>
<p>Ф.И.О. - {{ users.name }}</p>


<p>Участок - {{ users.uch }}</p>

<p>Профессия - {{ users.prof }}.</p>
	<!--
<p>{{ users.pp }}</p>
<p>{{ users.shu }}</p>

-->
<!--<h5>{{ users.id }}</h5>-->
<div class="row mx-auto ">
    <div class="col-sm">

        <a class="btn btn-secondary" href="/ekzamen/usersview/"  role="button">Назад</a>


	        <a class="btn btn-warning" href="{% url 'users_update' pk=users.id %}" role="button">Изменить</a>


                 <a class="btn btn-danger" href="/ekzamen/delete/{{users.id}}" role="button">Удалить</a>

	</div>

</div>
</center>


	</div>


</div>



{% endblock %}
          {% block title %}
Управление работником
    {% endblock %}

templates/ekzamenator/users_list.html
{% extends "ekzamenator/basic.html" %}


{% block content %}



<main class="bg-dark">
  <div class="container-fluid  bg-dark " style="height: 600px">
    <div class="row bg-dark mt-4">

<div class="table-responsive shadow py-4">


    <table class="table table-bordered bg-dark table-dark table-hover"><thead><tr>
    <th scope="col">Таб.№</th><th scope="col">Ф.И.О.</th><th scope="col">Участок</th><th scope="col">Профессия</th></tr></thead><tbody>



    {% for p1 in users_list %}

<tr>
<td>{{ p1.nomer }}</td>
<td><a href="{{ p1.get_absolute_url }}" class="editContent">
    <span class="fa fa-user fa-1x" aria-hidden="true"></span>
    {{ p1.name }}</a></td>
<td>{{ p1.uch }}</td>
    <td>{{ p1.prof }}</td>



</tr>
{% endfor %}<!--

{% for p2 in new_users %}

<tr>
<td>{{ p2.nomer }}</td>
<td><a href="{{ p2.get_absolute_url }}" class="editContent">{{ p2.name }}</a></td>
<td>{{ p2.uch }}</td>
    <td>{{ p2.prof }}.</td>



</tr>
{% endfor %}
-->


</tbody></table>
</div>
    </div>





    </div>
</main>

<div  class="text-success">
<h5>
    Найдено :{{ page_obj.paginator.count }} - человек на странице :{{ users_list.count }}
</h5>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следущея</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock %}
          {% block title %}
Список работников шахты
    {% endblock %}